//go:build !ignore_autogenerated

/*
Copyright 2026 Patrick Ajah.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlarmsSpec) DeepCopyInto(out *AlarmsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlarmsSpec.
func (in *AlarmsSpec) DeepCopy() *AlarmsSpec {
	if in == nil {
		return nil
	}
	out := new(AlarmsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDependencies) DeepCopyInto(out *AppDependencies) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDependencies.
func (in *AppDependencies) DeepCopy() *AppDependencies {
	if in == nil {
		return nil
	}
	out := new(AppDependencies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppDependencies) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDependenciesList) DeepCopyInto(out *AppDependenciesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppDependencies, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDependenciesList.
func (in *AppDependenciesList) DeepCopy() *AppDependenciesList {
	if in == nil {
		return nil
	}
	out := new(AppDependenciesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppDependenciesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDependenciesSpec) DeepCopyInto(out *AppDependenciesSpec) {
	*out = *in
	if in.SQS != nil {
		in, out := &in.SQS, &out.SQS
		*out = new(SQSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SNS != nil {
		in, out := &in.SNS, &out.SNS
		*out = new(SNSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Spec)
		(*in).DeepCopyInto(*out)
	}
	if in.DynamoDB != nil {
		in, out := &in.DynamoDB, &out.DynamoDB
		*out = new(DynamoDBSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KMS != nil {
		in, out := &in.KMS, &out.KMS
		*out = new(KMSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Alarms != nil {
		in, out := &in.Alarms, &out.Alarms
		*out = new(AlarmsSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDependenciesSpec.
func (in *AppDependenciesSpec) DeepCopy() *AppDependenciesSpec {
	if in == nil {
		return nil
	}
	out := new(AppDependenciesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDependenciesStatus) DeepCopyInto(out *AppDependenciesStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]ManagedResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDependenciesStatus.
func (in *AppDependenciesStatus) DeepCopy() *AppDependenciesStatus {
	if in == nil {
		return nil
	}
	out := new(AppDependenciesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumeRef) DeepCopyInto(out *ConsumeRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumeRef.
func (in *ConsumeRef) DeepCopy() *ConsumeRef {
	if in == nil {
		return nil
	}
	out := new(ConsumeRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoDBBackupSpec) DeepCopyInto(out *DynamoDBBackupSpec) {
	*out = *in
	if in.RetentionDays != nil {
		in, out := &in.RetentionDays, &out.RetentionDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoDBBackupSpec.
func (in *DynamoDBBackupSpec) DeepCopy() *DynamoDBBackupSpec {
	if in == nil {
		return nil
	}
	out := new(DynamoDBBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoDBOverrides) DeepCopyInto(out *DynamoDBOverrides) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoDBOverrides.
func (in *DynamoDBOverrides) DeepCopy() *DynamoDBOverrides {
	if in == nil {
		return nil
	}
	out := new(DynamoDBOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoDBSpec) DeepCopyInto(out *DynamoDBSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]DynamoDBTableSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Consumes != nil {
		in, out := &in.Consumes, &out.Consumes
		*out = make([]ConsumeRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoDBSpec.
func (in *DynamoDBSpec) DeepCopy() *DynamoDBSpec {
	if in == nil {
		return nil
	}
	out := new(DynamoDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoDBTableSpec) DeepCopyInto(out *DynamoDBTableSpec) {
	*out = *in
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(DynamoDBBackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SharedWith != nil {
		in, out := &in.SharedWith, &out.SharedWith
		*out = make([]SharedWithEntry, len(*in))
		copy(*out, *in)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(DynamoDBOverrides)
		**out = **in
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(EncryptionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoDBTableSpec.
func (in *DynamoDBTableSpec) DeepCopy() *DynamoDBTableSpec {
	if in == nil {
		return nil
	}
	out := new(DynamoDBTableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionSpec) DeepCopyInto(out *EncryptionSpec) {
	*out = *in
	if in.KMSKeyRef != nil {
		in, out := &in.KMSKeyRef, &out.KMSKeyRef
		*out = new(ConsumeRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionSpec.
func (in *EncryptionSpec) DeepCopy() *EncryptionSpec {
	if in == nil {
		return nil
	}
	out := new(EncryptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KMSKeySpec) DeepCopyInto(out *KMSKeySpec) {
	*out = *in
	if in.SharedWith != nil {
		in, out := &in.SharedWith, &out.SharedWith
		*out = make([]SharedWithEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KMSKeySpec.
func (in *KMSKeySpec) DeepCopy() *KMSKeySpec {
	if in == nil {
		return nil
	}
	out := new(KMSKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KMSSpec) DeepCopyInto(out *KMSSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]KMSKeySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Consumes != nil {
		in, out := &in.Consumes, &out.Consumes
		*out = make([]ConsumeRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KMSSpec.
func (in *KMSSpec) DeepCopy() *KMSSpec {
	if in == nil {
		return nil
	}
	out := new(KMSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResource) DeepCopyInto(out *ManagedResource) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	if in.LastVerifiedAt != nil {
		in, out := &in.LastVerifiedAt, &out.LastVerifiedAt
		*out = (*in).DeepCopy()
	}
	if in.PendingDeletionSince != nil {
		in, out := &in.PendingDeletionSince, &out.PendingDeletionSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResource.
func (in *ManagedResource) DeepCopy() *ManagedResource {
	if in == nil {
		return nil
	}
	out := new(ManagedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BackupSpec) DeepCopyInto(out *S3BackupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BackupSpec.
func (in *S3BackupSpec) DeepCopy() *S3BackupSpec {
	if in == nil {
		return nil
	}
	out := new(S3BackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BucketSpec) DeepCopyInto(out *S3BucketSpec) {
	*out = *in
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(S3BackupSpec)
		**out = **in
	}
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = new(S3ReplicationSpec)
		**out = **in
	}
	if in.SharedWith != nil {
		in, out := &in.SharedWith, &out.SharedWith
		*out = make([]SharedWithEntry, len(*in))
		copy(*out, *in)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(S3Overrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(EncryptionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BucketSpec.
func (in *S3BucketSpec) DeepCopy() *S3BucketSpec {
	if in == nil {
		return nil
	}
	out := new(S3BucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3LifecycleRule) DeepCopyInto(out *S3LifecycleRule) {
	*out = *in
	if in.TransitionAfterDays != nil {
		in, out := &in.TransitionAfterDays, &out.TransitionAfterDays
		*out = new(int32)
		**out = **in
	}
	if in.ExpirationAfterDays != nil {
		in, out := &in.ExpirationAfterDays, &out.ExpirationAfterDays
		*out = new(int32)
		**out = **in
	}
	if in.NoncurrentVersionExpirationAfterDays != nil {
		in, out := &in.NoncurrentVersionExpirationAfterDays, &out.NoncurrentVersionExpirationAfterDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3LifecycleRule.
func (in *S3LifecycleRule) DeepCopy() *S3LifecycleRule {
	if in == nil {
		return nil
	}
	out := new(S3LifecycleRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Overrides) DeepCopyInto(out *S3Overrides) {
	*out = *in
	if in.VersioningEnabled != nil {
		in, out := &in.VersioningEnabled, &out.VersioningEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LifecycleRules != nil {
		in, out := &in.LifecycleRules, &out.LifecycleRules
		*out = make([]S3LifecycleRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Overrides.
func (in *S3Overrides) DeepCopy() *S3Overrides {
	if in == nil {
		return nil
	}
	out := new(S3Overrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ReplicationSpec) DeepCopyInto(out *S3ReplicationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ReplicationSpec.
func (in *S3ReplicationSpec) DeepCopy() *S3ReplicationSpec {
	if in == nil {
		return nil
	}
	out := new(S3ReplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Spec) DeepCopyInto(out *S3Spec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]S3BucketSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Consumes != nil {
		in, out := &in.Consumes, &out.Consumes
		*out = make([]ConsumeRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Spec.
func (in *S3Spec) DeepCopy() *S3Spec {
	if in == nil {
		return nil
	}
	out := new(S3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SNSOverrides) DeepCopyInto(out *SNSOverrides) {
	*out = *in
	if in.ContentBasedDeduplication != nil {
		in, out := &in.ContentBasedDeduplication, &out.ContentBasedDeduplication
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SNSOverrides.
func (in *SNSOverrides) DeepCopy() *SNSOverrides {
	if in == nil {
		return nil
	}
	out := new(SNSOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SNSSpec) DeepCopyInto(out *SNSSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]SNSTopicSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Consumes != nil {
		in, out := &in.Consumes, &out.Consumes
		*out = make([]ConsumeRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SNSSpec.
func (in *SNSSpec) DeepCopy() *SNSSpec {
	if in == nil {
		return nil
	}
	out := new(SNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SNSTopicSpec) DeepCopyInto(out *SNSTopicSpec) {
	*out = *in
	if in.SharedWith != nil {
		in, out := &in.SharedWith, &out.SharedWith
		*out = make([]SharedWithEntry, len(*in))
		copy(*out, *in)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(SNSOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(EncryptionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SNSTopicSpec.
func (in *SNSTopicSpec) DeepCopy() *SNSTopicSpec {
	if in == nil {
		return nil
	}
	out := new(SNSTopicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQSOverrides) DeepCopyInto(out *SQSOverrides) {
	*out = *in
	if in.VisibilityTimeoutSeconds != nil {
		in, out := &in.VisibilityTimeoutSeconds, &out.VisibilityTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MaxReceiveCount != nil {
		in, out := &in.MaxReceiveCount, &out.MaxReceiveCount
		*out = new(int32)
		**out = **in
	}
	if in.ContentBasedDeduplication != nil {
		in, out := &in.ContentBasedDeduplication, &out.ContentBasedDeduplication
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQSOverrides.
func (in *SQSOverrides) DeepCopy() *SQSOverrides {
	if in == nil {
		return nil
	}
	out := new(SQSOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQSQueueSpec) DeepCopyInto(out *SQSQueueSpec) {
	*out = *in
	if in.SharedWith != nil {
		in, out := &in.SharedWith, &out.SharedWith
		*out = make([]SharedWithEntry, len(*in))
		copy(*out, *in)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(SQSOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(EncryptionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQSQueueSpec.
func (in *SQSQueueSpec) DeepCopy() *SQSQueueSpec {
	if in == nil {
		return nil
	}
	out := new(SQSQueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQSSpec) DeepCopyInto(out *SQSSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]SQSQueueSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Consumes != nil {
		in, out := &in.Consumes, &out.Consumes
		*out = make([]ConsumeRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQSSpec.
func (in *SQSSpec) DeepCopy() *SQSSpec {
	if in == nil {
		return nil
	}
	out := new(SQSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedWithEntry) DeepCopyInto(out *SharedWithEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedWithEntry.
func (in *SharedWithEntry) DeepCopy() *SharedWithEntry {
	if in == nil {
		return nil
	}
	out := new(SharedWithEntry)
	in.DeepCopyInto(out)
	return out
}
